// <auto-generated />
using System;
using AgendaFatec.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgendaFatec.Infrastructure.Migrations
{
    [DbContext(typeof(AgendaFatecDbContext))]
    [Migration("20260906180000_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AgendaFatec.Domain.Entities.AuditoriaLgpd", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DataHoraUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Detalhes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("EntidadeAfetada")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IpOrigem")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RegistroId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UsuarioEmail")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DataHoraUtc");

                    b.HasIndex("UsuarioId");

                    b.ToTable("AuditoriasLgpd", (string)null);
                });

            modelBuilder.Entity("AgendaFatec.Domain.Entities.Laboratorio", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("Capacidade")
                        .HasColumnType("int");

                    b.Property<bool>("CompartilhadoEtec")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Laboratorios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            Capacidade = 30,
                            CompartilhadoEtec = true,
                            Nome = "Laboratório 1"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            Capacidade = 30,
                            CompartilhadoEtec = true,
                            Nome = "Laboratório 2"
                        },
                        new
                        {
                            Id = 9,
                            Ativo = true,
                            Capacidade = 35,
                            CompartilhadoEtec = false,
                            Nome = "Laboratório 9"
                        },
                        new
                        {
                            Id = 10,
                            Ativo = true,
                            Capacidade = 35,
                            CompartilhadoEtec = false,
                            Nome = "Laboratório 10"
                        });
                });

            modelBuilder.Entity("AgendaFatec.Domain.Entities.Reserva", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Finalidade")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Justificativa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("LaboratorioId")
                        .HasColumnType("int");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("RecorrenciaGrupoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ResolvidoPorCoordenadorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RecorrenciaGrupoId");

                    b.HasIndex("ResolvidoPorCoordenadorId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("LaboratorioId", "DataInicio", "DataFim");

                    b.ToTable("Reservas", (string)null);
                });

            modelBuilder.Entity("AgendaFatec.Domain.Entities.SlotHorario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("ExclusivoEtec")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<TimeSpan>("HoraFim")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<int?>("LaboratorioId")
                        .HasColumnType("int");

                    b.Property<int>("Turno")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LaboratorioId");

                    b.ToTable("SlotsHorario", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            Descricao = "Manhã - Bloco 1 (07:30 - 08:20)",
                            ExclusivoEtec = false,
                            HoraFim = new TimeSpan(0, 8, 20, 0, 0),
                            HoraInicio = new TimeSpan(0, 7, 30, 0, 0),
                            Turno = 1
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            Descricao = "Manhã - Bloco 2 (08:20 - 09:10)",
                            ExclusivoEtec = false,
                            HoraFim = new TimeSpan(0, 9, 10, 0, 0),
                            HoraInicio = new TimeSpan(0, 8, 20, 0, 0),
                            Turno = 1
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            Descricao = "Manhã - Bloco 3 (09:20 - 10:10)",
                            ExclusivoEtec = false,
                            HoraFim = new TimeSpan(0, 10, 10, 0, 0),
                            HoraInicio = new TimeSpan(0, 9, 20, 0, 0),
                            Turno = 1
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            Descricao = "Manhã - Bloco 4 (10:10 - 11:00)",
                            ExclusivoEtec = false,
                            HoraFim = new TimeSpan(0, 11, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 10, 10, 0, 0),
                            Turno = 1
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            Descricao = "Manhã - Bloco 5 (11:10 - 12:00)",
                            ExclusivoEtec = false,
                            HoraFim = new TimeSpan(0, 12, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 11, 10, 0, 0),
                            Turno = 1
                        },
                        new
                        {
                            Id = 6,
                            Ativo = true,
                            Descricao = "Manhã - Bloco 6 (12:00 - 12:50)",
                            ExclusivoEtec = false,
                            HoraFim = new TimeSpan(0, 12, 50, 0, 0),
                            HoraInicio = new TimeSpan(0, 12, 0, 0, 0),
                            Turno = 1
                        },
                        new
                        {
                            Id = 7,
                            Ativo = true,
                            Descricao = "Noite - Bloco 1 (18:40 - 19:30)",
                            ExclusivoEtec = false,
                            HoraFim = new TimeSpan(0, 19, 30, 0, 0),
                            HoraInicio = new TimeSpan(0, 18, 40, 0, 0),
                            Turno = 3
                        },
                        new
                        {
                            Id = 8,
                            Ativo = true,
                            Descricao = "Noite - Bloco 2 (19:30 - 20:20)",
                            ExclusivoEtec = false,
                            HoraFim = new TimeSpan(0, 20, 20, 0, 0),
                            HoraInicio = new TimeSpan(0, 19, 30, 0, 0),
                            Turno = 3
                        },
                        new
                        {
                            Id = 9,
                            Ativo = true,
                            Descricao = "Noite - Bloco 3 (20:20 - 21:10)",
                            ExclusivoEtec = false,
                            HoraFim = new TimeSpan(0, 21, 10, 0, 0),
                            HoraInicio = new TimeSpan(0, 20, 20, 0, 0),
                            Turno = 3
                        },
                        new
                        {
                            Id = 10,
                            Ativo = true,
                            Descricao = "Noite - Bloco 4 (21:20 - 22:10)",
                            ExclusivoEtec = false,
                            HoraFim = new TimeSpan(0, 22, 10, 0, 0),
                            HoraInicio = new TimeSpan(0, 21, 20, 0, 0),
                            Turno = 3
                        },
                        new
                        {
                            Id = 11,
                            Ativo = true,
                            Descricao = "Noite - Bloco 5 (22:10 - 23:00)",
                            ExclusivoEtec = false,
                            HoraFim = new TimeSpan(0, 23, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 22, 10, 0, 0),
                            Turno = 3
                        });
                });

            modelBuilder.Entity("AgendaFatec.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Perfil")
                        .HasColumnType("int");

                    b.Property<string>("SigaId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("SigaId")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("AgendaFatec.Domain.Entities.Reserva", b =>
                {
                    b.HasOne("AgendaFatec.Domain.Entities.Laboratorio", "Laboratorio")
                        .WithMany("Reservas")
                        .HasForeignKey("LaboratorioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgendaFatec.Domain.Entities.Usuario", "ResolvidoPorCoordenador")
                        .WithMany()
                        .HasForeignKey("ResolvidoPorCoordenadorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AgendaFatec.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Reservas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Laboratorio");

                    b.Navigation("ResolvidoPorCoordenador");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AgendaFatec.Domain.Entities.SlotHorario", b =>
                {
                    b.HasOne("AgendaFatec.Domain.Entities.Laboratorio", "Laboratorio")
                        .WithMany("SlotsHorario")
                        .HasForeignKey("LaboratorioId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Laboratorio");
                });

            modelBuilder.Entity("AgendaFatec.Domain.Entities.Laboratorio", b =>
                {
                    b.Navigation("Reservas");

                    b.Navigation("SlotsHorario");
                });

            modelBuilder.Entity("AgendaFatec.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
